<?php

/**
 * Implementation of hook_perm().
 */
function divine_guru_availability_perm() {
  return array('select packages','manage availability');
}

/**
 * Implementation of hook_access().
 */
function divine_guru_availability_access($op, $account) {
  if ($op == 'create') {
    return user_access('select packages');
  }
  elseif ($op == 'update') {
    if (user_access('select packages')) {
      return TRUE;
    }
    else {
      return NULL;
    }
  } 
}

/**
 * Implementation of hook_menu().
 */
function divine_guru_availability_menu() {

  $items = array();

	$items['guru-availability/availability'] = array(
	'title' => 'Time Slot',
	'description' => 'Choose your availability',
	'page callback' => 'enter_availability',
	'access arguments' => array('manage availability'),
	);

	$items['guru-availability/fetch-availability'] = array(
	//'title' => 'Available Time Slots',
	'type' => MENU_CALLBACK,
	'description' => 'Choose your availability',
	'page callback' => 'fetch_availability',
	'access arguments' => array('manage availability'),
	);

	$items['guru-availability/display-availability/%'] = array(
	'title' => 'Time Slot',
	'description' => 'Choose your availability',
	'page callback' => 'show_availability',
	'page arguments' => array(2),
	'access arguments' => array('manage availability'),
	);

	$items['guru-availability/display-weekly-availability'] = array(
	'title' => 'Display Time Slot',
	'page callback' => 'show_availability_week_format',
	'page arguments' => array(2),
	'access arguments' => array('manage availability'),
	);

	$items['guru-availability/add_availability'] = array(
	'page callback' => 'save_availability',
	'access arguments' => array('manage availability'),
	);

  return $items;
}

function enter_availability() {
   return enter_availability_form();
}

function show_availability($count=0,$error='') {
   return enter_availability_form($count,$error);
}

/**
 * This function is used for checking whether this user mapped himself/herself with any packages or not
 */
function check_guru_packages(){
  global $user;
  $uid=$user->uid;
  $cnt=0;
  $query="select count(*) as cnt from {divine_guru_package} where uid=%d";
  $db_result = db_query($query,$uid);
  while ($row = db_fetch_object($db_result)) {
     $cnt=$row->cnt;
  }

  if($cnt){
   return true;
  }
  else{
   return false;
  }
}

/**
 * This function is used for displaying the calendar UI
 */
function enter_availability_form($month_counter=0,$error='') {
  global $user,$base_url;
  $uid=$user->uid;

  $module_path=drupal_get_path('module', 'divine_guru_availability');
  
  /*Add css and js files for popup functionality*/
  drupal_add_css($module_path.'/popup.css','module');
  drupal_add_js($module_path.'/popup.js','module');
  
  drupal_add_js('var jsURL="'.$base_url.'/guru-availability/"','inline');
  
  if(!check_user_role()){ //this function is defined in mapping module
    return 'You are not authorised to access this feature';
  }

  if(!check_guru_packages()){
    return 'Yoy have not assigned any packages.Please assign at least one package to continue.';
  }

  if(!is_numeric($month_counter) or $month_counter<0){
     drupal_set_message('Invalid month specified');
     drupal_goto('guru-availability/availability');
  }

  $prev_month_counter='';
  $next_month_counter='';
  $current_month_counter='';
  
  //FETCH TIME ZONE INFORMATION
  $query="select t.name from {divine_timezone} t, {users} u where t.tid=u.tid and u.uid=%d";
  $db_result = db_query($query);
  
  $timezoneFlag = 0 ;
  $timezone_name='---';
  while ($row = db_fetch_object($db_result)) {
    $timezoneFlag = 1;
    $timezone_name = $row->name;
  }

  $editTimezoneLink = l('Edit your time zone','user/'.$uid.'/edit');
  $timezoneDivString = '<div style="width:100%">
                         <div style="width:70%;float:left;">
			  Your Time Zone is : <b>'.$timezone_name.'</b>&nbsp;&nbsp;
			 </div>
			 <div style="float:right">
			  '.$editTimezoneLink.'
			 </div>
			</div><div style="clear:both"></div>';

  if(!$timezoneFlag){ // if no time zone is selected then do not allow to proceed
    $addTimezoneLink = l('Click on this link to add your time zone.','user/'.$uid.'/edit');
    return 'You need to add your time zone to use this feature.&nbsp;&nbsp;'.$addTimezoneLink;
  }

  if($month_counter>0){
   $prev_month_counter='<div style="float:left;width:33%">'.l(t('<< Previous Month'),'guru-availability/display-availability/'.($month_counter-1)).'</div>';
  }
  else{
    $prev_month_counter='<div style="float:left;width:33%">&nbsp;</div>';
  }
  $next_month_counter='<div style="float:right;width:33%;text-align:right">'.l(t('Next Month >>'),'guru-availability/display-availability/'.($month_counter+1)).'</div>';

  $current_month_counter='<div style="float:left;width:33%;text-align:center">'.l(t('Current Month'),'guru-availability/display-availability/0').'</div>';

  $navaigation_string=$prev_month_counter.$current_month_counter.$next_month_counter.'<div style="clear:both"></div>';

  /*CALENDAR VIEW STARTS*/
    
    $current_date=date("Y-m-d");
    $current_timestamp=strtotime($current_date);
    $date=strtotime("+".$month_counter." month",$current_timestamp);

    $day   = date('d', $date) ;
    $month = date('m', $date) ;
    $year  = date('Y', $date) ;

    $first_day = mktime(0,0,0,$month, 1, $year) ;

    $title = date('F', $first_day) ; 

    $day_of_week = date('D', $first_day) ; 

    switch($day_of_week){ 
     case "Sun": $blank = 0; break; 
     case "Mon": $blank = 1; break; 
     case "Tue": $blank = 2; break; 
     case "Wed": $blank = 3; break; 
     case "Thu": $blank = 4; break; 
     case "Fri": $blank = 5; break; 
     case "Sat": $blank = 6; break; 
   }

   $days_in_month = cal_days_in_month(0, $month, $year) ;
   
   $table_string='';
    $table_string ="<table border='1' width='294'>";
    $table_string .="<tr><td colspan='7' align='center'><b> $title $year </b></td></tr>";
    $table_string .= "<tr><td width='42' align='center'>Sun</td><td width='42' align='center'>Mon</td><td 
         width='42' align='center'>Tue</td><td width='42' align='center'>Wed</td><td width='42' align='center'>Thu</td><td 
	 width='42' align='center'>Fri</td><td width='42' align='center'>Sat</td></tr>";
 
  $day_count = 1;

  $table_string .= "<tr>";
  while ( $blank > 0 ){ 
    $table_string .= "<td></td>"; 
    $blank = $blank-1; 
    $day_count++;
  } 

  $day_num = 1;
  while ( $day_num <= $days_in_month ){
    if($day_num<10){
      $tday_num="0".$day_num;
    }
    else{
      $tday_num=$day_num;
    }
    $present_timestamp=strtotime($year."-".$month."-".$tday_num);
    if($present_timestamp >= $current_timestamp ){
      $day_num_string='<a href="javascript:void(0);" title="Click to open time slots information" onclick="centerPopup();loadPopup('.$present_timestamp.');">'.t($day_num).'</a>';
    }
    else{
      $day_num_string=$day_num;
    }
    $table_string .= "<td align='center'> $day_num_string </td>"; 
    $day_num++; 
    $day_count++;
    if ($day_count > 7){
     $table_string .= "</tr><tr>";
     $day_count = 1;
    }
  } 

 while ( $day_count >1 && $day_count <=7 ){ 
   $table_string .= "<td> </td>"; 
   $day_count++; 
 } 

 $table_string .= "</tr></table>";

 $popup_string='<form name="time_slot_form" id="time_slot_form" method="" action="" onsubmit="return false;">
                 <input type="hidden" name="sel_date" id="sel_date" value="" />
                 <div id="popupContact">
		 <a id="popupContactClose" style="cursor:pointer" title="Close"><b>x</b></a>
		 <p id="contactArea">			
		 </p>
	        </div>
	       <div id="backgroundPopup"></div>
	       </form>';

$blockPageDivString = '<div id="blockPopup" style="display:none;position:fixed;_position:absolute;height:100%;width:100%;top:0;
left:0;background:#000000;border:1px solid #cecece;z-index:1;" align="center">
                      <div style="border:1px solid black; display:block; padding:5px; background-color:#fbffb3; color:#000; width:200px;"><b>Please Wait......</b></div>
                   </div>';

/*CALENDAR VIEW ENDS*/

  return  $timezoneDivString
          .$navaigation_string
          .$table_string
	  .$navaigation_string
	  .$popup_string.'<div style="clear:both"></div>'.$blockPageDivString.'<div style="clear:both"></div>';
}

/**
 * This function is used for fetching time slots information and
 * already selected time slots for this user
 */
function fetch_availability(){

 global $user;
 $timestamp=trim($_POST['ts']);
 if($timestamp==''){
   echo 'Invalid date selected';
   return;
 }
 $dated=date("Y-m-d",$timestamp);
 if(!dated){
  echo 'Invalid date selected';
  return;
 }
 $front_end_date=date("d F,Y",$timestamp);

 $uid=$user->uid;

 /*FETCH RECORDS FROM AVAILIBILITY TABLE*/
  $query="select ga.uid,ga.sid,ga.dated,ga.isAvailable
          from {divine_guru_availability} ga
	  where ga.uid=%d and ga.dated ='%s'";
     
  $db_result = db_query($query,$uid,$dated);

  $existing_records=array();
  $booked_timeslots_array=array();
  while ($row = db_fetch_object($db_result)) {
      $existing_records[] = $row->uid.'-'.$row->sid.'-'.$row->dated;
      if($row->isAvailable=='0'){ //time slots are already booked by the user
       $booked_timeslots_array[] = $row->uid.'-'.$row->sid.'-'.$row->dated;
      }
  }

  /*FETCH RECORDS FROM SLOTS TABLE*/
  $query="select sid,name from {divine_time_slot}";
     
  $db_result = db_query($query);

  $rows=array();
  $flag=false;

  $records_per_row=4;

  $table_string ='<h1>Select your time slots for '.$front_end_date.'</h1>';
  $table_string .='<table border="1" cellpadding="0" cellspacing="0">';
  $table_string .='<tr><td colspan="'.$records_per_row.'" align="center"><b>List of time slots</b></td></tr>';
  $table_string .='<tr>';
  $cnt=0;
  while ($row = db_fetch_object($db_result)) {
      $flag=true;
      $key=$uid.'-'.$row->sid.'-'.$dated;
      $style='';
      if($key==$error){
	$style='style="border:1px solid red"';
      }
      $checked='';
      if(in_array($key,$existing_records)){
	$checked='checked';
      }
      if(in_array($key,$booked_timeslots_array)){
        $row->name ='<span style="color:red">'.$row->name.'</span>';
      }
      $checkbox='<input type="checkbox" name="avail_chk[]" value="'.$key.'" '.$checked.'  '.$style.' />&nbsp;'.$row->name;
      if($cnt==$records_per_row){
        $cnt=0;
	$table_string .='</tr><tr>';
      }
      $cnt ++;
      $table_string .='<td>'.$checkbox.'</td>';
    }
    if(!$flag){
      $table_string .='<td colspan="'.$records_per_row.'">No time slots found</td></tr></table>';
    }
    else{
      for(; $cnt < $records_per_row; $cnt++){
        $table_string .='<td></td>';
      }
      $table_string .='</tr>
          <tr>
	    <td colspan="'.$records_per_row.'" align="left">
	     Copy this availability for this 
	      <input type="radio" id="copyRadio1" name="copyRadio" value="1" />&nbsp;week or
	      <input type="radio" id="copyRadio2" name="copyRadio" value="2" />&nbsp;month
	    </td>
	  </tr>
          <tr><td colspan="'.$records_per_row.'" align="center">
          <input type="submit" value="Save" onclick="saveData();" />
	  &nbsp;<input type="button" value="Cancel" onclick="disablePopup();" /></td></tr>
	  <tr><td colspan="'.$records_per_row.'" align="left">* Time slots colored in red are booked by users.</td></tr>';
      $table_string .='</table>';
    }

    echo $table_string;
    return;

}


/**
 * This function will calculate last date of the week
 */
function lastDaysOfWeek($date) {
    $ts = strtotime($date);
    $start = (date('w', $ts) == 0) ? $ts : strtotime('last sunday', $ts);
    $start_date = date('Y-m-d', $start);
    return $end_date = date('Y-m-d', strtotime('next saturday', $start));
}


/**
 * This function is saving time slot availability of this user
 */
function save_availability(){
  global $user;
  $uid=$user->uid;

  if(!check_user_role()){ //this function is defined in mapping module
    echo 'You are not authorised to access this feature';
    return;
  }

  if(!check_guru_packages()){
    echo 'Yoy have not assigned any packages.Please assign at least one package to continue.';
    return;
  }

  $avail_chk=$_POST['avail_chk'];
  $date_timestamp=$_POST['sel_date'];
  $selected_date=date("Y-m-d",$date_timestamp);
  $selected_end_date=$date_timestamp;

  $monthLastDay = strtotime(date("Y-m-d",mktime(0, 0, 0, (date('m',$date_timestamp) + 1), 0, date('Y',$date_timestamp))));
  $weekLastDay  = strtotime(lastDaysOfWeek($selected_date));

  $tempStartDate=strtotime($selected_date);

  //echo 'T='.date("Y-m-d",$tempStartDate).'***'.'L='.date("Y-m-d",$weekLastDay);
 
  $copy=trim($_POST['copyRadio']);
  if($copy=='1'){
   while($tempStartDate <= $weekLastDay){
      if($tempStartDate==$monthLastDay){
        $selected_end_date =$tempStartDate;
	break;
      }
      $selected_end_date = $tempStartDate;
      $tempStartDate = strtotime("+1 days",$tempStartDate);
   }
  }
  else if($copy=='2'){
    $selected_end_date=$monthLastDay;
  }


  if(!$selected_date){
    echo 'Invalid date specified.';
    return;
  }
  
  if($avail_chk==''){
   $avail_chk=array();
  }
  $count=count($avail_chk);

  $tempStartDate=strtotime($selected_date);


  /*****START TRANSACTION*****/
  $query = "START TRANSACTION";
  $ret   = db_query($query);
  if(!$ret){
    echo 'Data could not be saved';
    return;
  }

  //copying starts
  while( $tempStartDate <= $selected_end_date){

   //set timezone to UTC
   date_default_timezone_set("UTC");
   
   $selected_date = date("Y-m-d",$tempStartDate);

  /*CHECK CLASHING WITH BOOKING.*/

   /*FETCH RECORDS FROM AVAILIBILITY TABLE WHICH ARE BOOKED BY NORMAL USERS*/
   $query="select ga.sid,ga.isAvailable,s.name
           from {divine_guru_availability} ga, {divine_time_slot} s 
	   where ga.sid=s.sid and ga.uid=%d and ga.dated='%s'";
     
   $db_result = db_query($query,$uid,$selected_date);

   $booked_records=array();
   $not_booked_records=array();
   $sid_name_array=array();
   while ($row = db_fetch_object($db_result)) {
      if($row->isAvailable=='0'){
        $booked_records[] = $row->sid;
	$sid_name_array[$row->sid]=$row->name;
      }
      else{
        $not_booked_records[] = $row->sid;
      }
   }
   
   $booked_count=count($booked_records);

   $sid_array=array();
   for($i=0; $i<$count; $i++){
     $arr=explode('-',$avail_chk[$i]);
     $sid=trim($arr[1]);
     if($sid==''){
       echo 'Invalid time slot selected.';
       return;
     }
     $sid_array[]=$sid;
   }

   for($i=0; $i<$booked_count; $i++){
      /*EITHER STRICT CHECK OR MAIL WILL BE SEND TO AFFECTED USERSS*/
      if(!in_array($booked_records[$i],$sid_array)){
        echo "( ".$sid_name_array[$booked_records[$i]]." ) time slot is booked by an user on ".date("d F,Y",$tempStartDate).".\nYou can not de-assign from it.";
        return;
      }
   }

 
  //Fetch user's time zone information and calculating adjustment needed
  $query="select t.tid,t.offsettime,t.offsetsign,t.timezone
          from {divine_timezone} t, {users} u
	  where u.tid=t.tid and u.uid=%d";

  $db_result = db_query($query,$uid);

  $adjusted_time=0;
  $offset_time=0;
  $offset_sign=0;
  $timezone=0;
  $timezone_name='';
  $isDst=0;
  while ($row = db_fetch_object($db_result)) {
      $offset_time = $row->offsettime;
      $offset_sign = $row->offsetsign;
      $timezone    = $row->tid;
      $timezone_name= $row->timezone;
      if($timezone_name!=''){
       @date_default_timezone_set($timezone_name); //to suppress warnings for not supported timezones
       $isDst = date("I");
      }
  }
  if($offset_time!=0){
    $arr=explode(':',$offset_time);
    $adjusted_time=$arr[0]*60*60+$arr[1]*60;
    if($offset_sign=='1'){
     if($isDst==1){
       $adjusted_time = $adjusted_time + 3600 ; //for DST
     }
     $adjusted_time=0-$adjusted_time;
    }
    else{
      if($isDst==1){
         $adjusted_time = $adjusted_time - 3600 ; //for DST
      }
    }
  }

  //echo $adjusted_time.'--'.$offset_sign.'---'.$isDst."\n";
  //die;

  //set timezone to UTC
  date_default_timezone_set("UTC");
  
  /*BUILD INSERT QUERY*/
  
  $insert_query='';
  for($i=0; $i<$count; $i++){

     $data=explode('-',$avail_chk[$i]);
     $slotid=$data[1];

     $query="select aid from {divine_guru_availability} where uid=%d and sid=%d and dated='%s'";
     $db_result = db_query($query,$uid,$slotid,$selected_date);
     $aid='';
     while ($row = db_fetch_object($db_result)) {
      $aid = $row->aid;
     }
     if($aid==''){
       //fetch slot information
       $query="select start_time,end_time
               from {divine_time_slot} where sid=%d";
       $db_result = db_query($query,$slotid);
       $start_time=''; $end_time='';

       while ($row = db_fetch_object($db_result)) {
	$start_time=$row->start_time;
	$end_time=$row->end_time;
       }

       $start_timestamp=strtotime(date($selected_date.' '.$start_time)) + $adjusted_time;
       $end_timestamp=strtotime(date($selected_date.' '.$end_time)) + $adjusted_time;
       //echo date('Y-m-d g:i:s A',$start_timestamp);
       //die;

       //do the insertion
       $insert_query ="insert into {divine_guru_availability} 
                      (uid,sid,dated,start_timestamp,end_timestamp,tid,isAvailable)
                      values (%d,%d,'%s',%d,%d,%d,%d)";
       db_query($insert_query,$uid,$slotid,$selected_date,$start_timestamp,$end_timestamp,$timezone,1);

     }
  }

  //DELETE UNCHEKED RECORDS
  $delete_query='';
  $not_booked_count=count($not_booked_records);
  for($i=0; $i<$not_booked_count; $i++){
    if(!in_array($not_booked_records[$i],$sid_array)){
      $delete_query="delete from {divine_guru_availability} 
                     where uid=%d and sid=%d and dated='%s'";
      db_query($delete_query,$uid,$not_booked_records[$i],$selected_date);
    }
  }

  $tempStartDate = strtotime("+1 days",$tempStartDate); //counter increments

 } // while loop ends

 /*****COMMIT TRANSACTION*****/
 $query = "COMMIT";
 $ret   = db_query($query);
  if(!$ret){
   echo 'Data could not be saved';
   return;
 }

  echo 'Time slot information saved';
  return;
}


/**
 * This function is used for displaying guru's availablity in week format
 * bookedByUserid = > id of the normal user who is viewing guru's availablity
 */
 function show_availability_week_format($week_counter=0){
  global $user;
  $gid=$user->uid;
  return show_guru_availability_week_format($gid,$week_counter);
 }

function show_guru_availability_week_format($gid,$week_counter=0,$bookedByUserid='',$type=1){

  /*
  if(!is_numeric($week_counter) or $week_counter>52 or $week_counter<0){
     drupal_set_message('Invalid date specified');
     return;
  }
  */

  $prev_week_counter='';
  $next_week_counter='';
  $current_week_counter='';
  if($week_counter>0){
   if($type!=2){
    $prev_week_counter='<div style="float:left;width:33%">'.l(t('Previous Week'),'guru-availability/display-weekly-availability/'.($week_counter-1)).'</div>';
   }
   else{
     $prev_week_counter='<div style="float:left;width:33%"><a href="javascript:void(0);" onclick="loadData('.$gid.','.($week_counter-1).')">'.t('Previous Week').'</a></div>';
   }
  }
  else{
    $prev_week_counter='<div style="float:left;width:33%">&nbsp;</div>';
  }
  
  /*
  if($week_counter<52){
   $next_week_counter='<div style="float:right;width:33%;text-align:right">'.l(t('Next Week'),'guru-availability/display-weekly-availability/'.($week_counter+1)).'</div>';
  }
  else{
    $next_week_counter='<div style="float:left;width:33%">&nbsp;</div>';
  }
  */

  if($type!=2){
    $next_week_counter='<div style="float:right;width:33%;text-align:right">'.l(t('Next Week'),'guru-availability/display-weekly-availability/'.($week_counter+1)).'</div>';
  }
  else{
    $next_week_counter='<div style="float:right;text-align:right;width:33%"><a href="javascript:void(0);" onclick="loadData('.$gid.','.($week_counter+1).')">'.t('Next Week').'</a></div>';
  }

  if($type!=2){
    $current_week_counter='<div style="float:left;width:33%;text-align:center">'.l(t('Curent Week'),'guru-availability/display-weekly-availability/0').'</div>';
  }
  else{
    $current_week_counter='<div style="float:left;text-align:center;width:33%"><a href="javascript:void(0);" onclick="loadData('.$gid.',0)">'.t('Curent Week').'</a></div>'; 
  }

  $navaigation_string=$prev_week_counter.$current_week_counter.$next_week_counter.'<div style="clear:both"></div>';

  $temp_week_counter=7*$week_counter;
  
  $current_date=date("Y-m-d");
  $date_timestamp=strtotime("+".$temp_week_counter." day",strtotime($current_date));
  
  $month=date("m",$date_timestamp);
  $year=date("Y",$date_timestamp);
  $day=date("d",$date_timestamp);

  $day_of_week=date("N",$date_timestamp);
  if($day_of_week==1){
   $monday_date=date("Y-m-d",$date_timestamp);
  }
  else{
   $monday_date=date("Y-m-d", mktime(0, 0, 0, $month, $day+(1-$day_of_week), $year));
  }

  if($day_of_week==7){
   $sunday_date=date("Y-m-d",$date_timestamp);
  }
  else{
   $sunday_date=date("Y-m-d", mktime(0, 0, 0, $month, $day+(7-$day_of_week), $year));
  }

  $monday_date_timestamp=strtotime($monday_date);
  $sunday_date_timestamp=strtotime($sunday_date);

  $tableString = '<table border="1" cellpadding="0" cellspacing="0">';
  $tableString .= '<tr>';

  $temp_timestamp=$monday_date_timestamp;
  while($temp_timestamp<=$sunday_date_timestamp){
       $tableString .= '<td align="center"><b>'.t(date("D",$temp_timestamp).'<br>'.date("d",$temp_timestamp).' '.date("M",$temp_timestamp).','.date("Y",$temp_timestamp)).'</td>';
       $temp_timestamp=strtotime("+1 day",$temp_timestamp).'</b>';  
  }
  $tableString .='</tr>';

  if($bookedByUserid==''){ //when guru himself views the time slots
   /*FETCH RECORDS FROM AVAILIBILITY TABLE*/
   $query="select ga.uid,ga.sid,ga.dated,ga.isAvailable
          from {divine_guru_availability} ga, {users} u , {divine_time_slot} dt
	  where ga.uid=u.uid and ga.sid=dt.sid 
	  and u.uid=%d and (ga.dated >='%s' and ga.dated <='%s')";
     
   $db_result = db_query($query,$gid,$monday_date,$sunday_date);
  }
  else{ //when member user view guru's time slots
    /*FETCH RECORDS FROM AVAILIBILITY TABLE*/
   $query="select ga.uid,ga.sid,ga.dated,ga.isAvailable,gb.uid as booked_by
          from {users} u , {divine_time_slot} dt,
	  {divine_guru_availability} ga
	  LEFT JOIN {divine_guru_booking} gb ON ga.aid=gb.aid
	  where ga.uid=u.uid and ga.sid=dt.sid 
	  and u.uid=%d and (ga.dated >='%s' and ga.dated <='%s')
          ";
     
   $db_result = db_query($query,$gid,$monday_date,$sunday_date);
  }

  $existing_records=array();
  $availabilityArray=array();
  $bookeByArray=array();
  while ($row = db_fetch_object($db_result)) {
    $existing_records[] = $row->uid.'-'.$row->sid.'-'.$row->dated;
    $availabilityArray[$row->uid.'-'.$row->sid.'-'.$row->dated] = $row->isAvailable;
    $bookeByArray[$row->uid.'-'.$row->sid.'-'.$row->dated] = $row->booked_by;
  }
  
  //echo '<pre>';
  //print_r($existing_records);

  /*FETCH RECORDS FROM AVAILIBILITY TABLE*/

  /*FETCH RECORDS FROM SLOTS TABLE*/
  $query="select sid,name from {divine_time_slot}";
     
  $db_result = db_query($query);

  $rows=array();
  $flag=false;
  while ($row = db_fetch_object($db_result)) {
      $tableString .='<tr>';

      $flag=true;
      $slotid=$row->sid;
      $slotname=$row->name;
      $temp_timestamp=$monday_date_timestamp;
      
      while($temp_timestamp<=$sunday_date_timestamp){
          $key=$gid.'-'.$slotid.'-'.date("Y-m-d",$temp_timestamp);
	 
	  $style='style="background-color:#e5e5e5"';
	  
	  if(in_array($key,$existing_records)){
	    if($availabilityArray[$key]=='1'){
             $style='style="background-color:#80ff80"';
	    }
	    else{
	     if($bookedByUserid!=''){
	       if($bookeByArray[$key]==$bookedByUserid){
	         $style='style="background-color:#80e1ec"';   
	       }
	       else{
	         $style='style="background-color:#ff3535"';
	       }
	     }
	     else{
	        $style='style="background-color:#ff3535"';
	     }
	    }
	  }
	  $tableString .= '<td '.$style.' align="center">'.$slotname.'</td>';
          $temp_timestamp=strtotime("+1 day",$temp_timestamp);  
      }

      $tableString .='</tr>';
  }

  if(!$flag){
    $tableString .= '<tr><td colspan="7">No Records Found</td></tr>';
  }

  /*
  $legends ='<table width="100px;">
                <tr>
		 <td style="background-color:#80ff80;">Available</td>
		 <td style="background-color:#ff3535;">Booked</td>
		 <td style="background-color:#d3d3d3;">Not Applicable</td>
                </tr>
              </table>'; 
   */
  
  /*
  $tableString .= '<tr>
                    <td align="left">Lengends : </td>
		    <td style="background-color:#80ff80;">Available</td>
		    <td style="background-color:#ff3535;">Booked</td>
		    <td style="background-color:#d3d3d3;">NA</td>
		    <td></td><td></td><td></td>
		   </tr>';
  */

  $tableString .= '</table>';

  return $navaigation_string.$tableString.$navaigation_string;

  if($bookedByUserid!=''){ 
    echo $navaigation_string.$tableString.$navaigation_string;
    return;
  }
  else{
    return $navaigation_string.$tableString.$navaigation_string;
  }
 }
?>